version: '3.7'
services:
  db:
    platform: linux/x86_64 #change platform to linux/amd64 if you are using M1 macbook with arm arch
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bareksa_news'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  cache:
    platform: linux/x86_64 #change platform to linux/amd64 if you are using M1 macbook with arm arch
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  my-db:
  cache:
    driver: local



 