CREATE TABLE IF NOT EXISTS topic (
	id INT NOT NULL AUTO_INCREMENT,
	`serial` CHAR(20) NOT NULL,
	title VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL,
	CONSTRAINT topic_pk PRIMARY KEY (id),
	UNIQUE KEY `idx_topic_serial_unique` (`serial`) USING  BTREE
)

ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;