CREATE TABLE IF NOT EXISTS tag (
	id INT NOT NULL AUTO_INCREMENT,
	`name` CHAR(40) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL,
	CONSTRAINT tag_pk PRIMARY KEY (id),
	UNIQUE KEY `idx_topic_name_unique` (`name`) USING BTREE
)

ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;